export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOG_OUT = 'LOG_OUT';
export const LOAD_PROFILE = 'LOAD_PROFILE';

export const HOMESCREEN_VIDEO_SUGGESTION_SUCCESS = 'HOME_VIDEOS_SUCCESS'
export const HOMESCREEN_VIDEOS_SUGGESTION_FAILS = 'HOME_VIDEOS_FAIL'
export const HOMESCREEN_VIDEOS_SUGGESTION_REQUEST = 'HOME_VIDEOS_REQUEST'

export const CHOSEN_VIDEO_SUCCESS = 'CHOSEN_VIDEO_SUCCESS';
export const CHOSEN_VIDEO_FAIL = 'CHOSEN_VIDEO_FAIL';
export const CHOSEN_VIDEO_REQUEST = 'CHOSEN_VIDEO_REQUEST';

export const CHANNEL_DETAILS_REQUEST = 'CHANNEL_DETAILS_REQUEST';
export const CHANNEL_DETAILS_SUCCESS = 'CHANNEL_DETAILS_SUCCESS';
export const CHANNEL_DETAILS_FAIL = 'CHANNEL_DETAILS_FAIL';

export const SUBSCRIPTION_STATUS = 'SUBSCRIPTION_STATUS';

export const COMMENT_LIST_SUCCESS = 'COMMENT_LIST_SUCCESS';
export const COMMENT_LIST_REQUEST = 'COMMENT_LIST_REQUEST';
export const COMMENT_LIST_FAIL = 'COMMENT_LIST_FAIL';

export const POST_COMMENT_SUCCESS = 'POST_COMMENT_SUCCESS';
export const POST_COMMENT_FAIL = 'POST_COMMENT_FAIL';

export const RELATED_VIDEOS_SUCCESS = 'RELATED_VIDEOS_SUCCESS';
export const RELATED_VIDEOS_REQUEST = 'RELATED_VIDEOS_REQUEST';
export const RELATED_VIDEOS_FAIL = 'RELATED_VIDEOS_FAIL';

export const SEARCH_VIDEO_SUCCESS = 'SEARCH_VIDEO_SUCCESS';
export const SEARCH_VIDEO_REQUEST = 'SEARCH_VIDEO_REQUEST';
export const SEARCH_VIDEO_FAIL = 'SEARCH_VIDEO_FAIL';

export const SUBSCRIBED_CHANNEL_SUCCESS = 'SUBSCRIBED_CHANNEL_SUCCESS';
export const SUBSCRIBED_CHANNEL_REQUEST = 'SUBSCRIBED_CHANNEL_REQUEST';
export const SUBSCRIBED_CHANNEL_FAIL = 'SUBSCRIBED_CHANNEL_FAIL';

export const CHANNEL_VIDEOS_SUCCESS = 'CHANNEL_VIDEOS_SUCCESS';
export const CHANNEL_VIDEOS_REQUEST = 'CHANNEL_VIDEOS_REQUEST';
export const CHANNEL_VIDEOS_FAIL = 'CHANNEL_VIDEOS_FAIL';
